[package]
name = "components"
version = "0.2.0"
authors = ["Kazuya Iimuro <ikazuya0201@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
heapless = "0.5.3"
generic-array = "0.13.2"
static_assertions = "1.1.0"
itertools = "0.9.0"
typenum = "1.12.0"
nb = "0.1.2"
auto_enums = "0.7.5"
libm = "0.2.1"

[dependencies.num]
version = "0.2"
default-features = false

[dependencies.heap]
version = "0.1.0"
git = "https://github.com/ikazuya0201/heap"

[dependencies.quantities]
version = "0.1.1"
git = "https://github.com/ikazuya0201/quantities"
