[package]
name = "components"
version = "0.1.0"
authors = ["Kazuya Iimuro <ikazuya0201@gmail.com>"]
edition = "2018"

[profile.dev]
opt-level = 3

[dependencies]
heapless = "0.5.3"
generic-array = "0.14.4"
typenum = "1.12.0"
nb = "0.1.2"
auto_enums = "0.7.5"

[dependencies.uom]
version = "0.30.0"
default-features = false
features = ["f32", "autoconvert", "si"]

[dependencies.num]
version = "0.2"
default-features = false

[dependencies.heap]
version = "0.1.1"
git = "https://github.com/ikazuya0201/heap"

[dev-dependencies]
approx = "0.3.2"
criterion = "0.3.3"
proptest = "0.10.1"
proptest-derive = "0.2.0"
utils = { path = "./utils" }

[features]
log = []

[[bench]]
name = "search_operator"
harness = false
