[package]
name = "mouse_main"
version = "0.1.0"
authors = ["Kazuya Iimuro <ikazuya0201@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
heapless = "0.5.3"
cortex-m = "0.6.0"
cortex-m-rt = "0.6.10"
panic_rtt = "0.2.0"
