name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      matrix:
        rustc: [stable, nightly]

    steps:
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rustc }}
        target: x86_64-unknown-linux-gnu
        components: clippy, rustfmt
        override: true
    - uses: davidB/rust-cargo-make@v1
    - uses: actions/checkout@v1
    - name: Run CI with ${{ matrix.rustc }}
      run: cargo make ci

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rustc }}
        override: true
        target: thumbv7em-none-eabihf
    - name: Build with ${{ matrix.rustc }} on native
      run: cargo build --target=thumbv7em-none-eabihf
