name: Rust

on:
  push:
    branches: [ master, develop/v0.2 ]
  pull_request:
    branches: [ master, develop/v0.2 ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        target: thumbv7em-none-eabihf
        override: true
    - name: Build
      run: cargo build --target=thumbv7em-none-eabihf --verbose -Zfeatures=dev_dep

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        target: x86_64-unknown-linux-gnu
        override: true
    - name: Test
      run: cargo test --target=x86_64-unknown-linux-gnu --verbose
    - name: Test Expensive
      run: cargo test --target=x86_64-unknown-linux-gnu --verbose --features="expensive_tests"
