name: Rust

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        target: thumbv7em-none-eabihf
        override: true
    - name: Build
      run: cargo build --target=thumbv7em-none-eabihf --verbose -Zfeatures=dev_dep

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        target: x86_64-unknown-linux-gnu
        override: true
    - name: Test
      run: cargo test --target=x86_64-unknown-linux-gnu --verbose
    - name: Test Ignored
      run: cargo test --target=x86_64-unknown-linux-gnu --verbose -- --ignored
    - name: DocTest
      run: cargo test --target=x86_64-unknown-linux-gnu --verbose --doc
    - name: Doc
      run: cargo doc --target=x86_64-unknown-linux-gnu --verbose
