name: Rust

on:
  push:
    branches: [ master, develop/v0.2 ]
  pull_request:
    branches: [ master, develop/v0.2 ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        repository: ikazuya0201/quantities
        token: ${{ secrets.ACCESS_TOKEN }}
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
    - name: Build
      run: cargo +nightly build --verbose
    - name: Run tests
      run: cargo +nightly test --verbose
