name: Rust

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      matrix:
        rustc: [stable, nightly]

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rustc }}
        target: thumbv7em-none-eabihf
        override: true
    - name: Build ${{ matrix.rustc }} on native
      run: cargo build --target=thumbv7em-none-eabihf --verbose

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rustc }}
        target: x86_64-unknown-linux-gnu
        components: clippy
        override: true
    - name: Clippy ${{ matrix.rustc }}
      run: cargo clippy --target=x86_64-unknown-linux-gnu --verbose -- -D warnings
    - name: Test ${{ matrix.rustc }}
      run: cargo test --target=x86_64-unknown-linux-gnu --verbose
    - name: Test ignored ${{ matrix.rustc }}
      run: cargo test --target=x86_64-unknown-linux-gnu --verbose -- --ignored
    - name: Doc ${{ matrix.rustc }}
      run: cargo doc --target=x86_64-unknown-linux-gnu --verbose
